version: '3.6'
services:
  gitlab:
    image: 'gitlab-jh.tencentcloudcr.com/omnibus/gitlab-jh:latest'
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      # external_url 必须设置域名及端口
      #   - 想使用非 80 端口
      #   - 部分模块链接会使用到，如 runner 编辑页
      GITLAB_OMNIBUS_CONFIG: |
         external_url '${SERVE_HOSTNAME}:${SERVE_WEB_PORT}'  #访问地址
         # 端口配置
         gitlab_rails['gitlab_shell_ssh_port'] = ${SERVE_SSH_PORT}
         # Email配置
         gitlab_rails['smtp_enable'] = true
         gitlab_rails['smtp_address'] = "smtp.qq.com"
         gitlab_rails['smtp_domain'] = "smtp.qq.com"
         gitlab_rails['smtp_port'] = 465
         gitlab_rails['smtp_user_name'] = "My Email"
         gitlab_rails['smtp_password'] = "授权码"
         gitlab_rails['smtp_authentication'] = "login"
         gitlab_rails['smtp_enable_starttls_auto'] = true
         gitlab_rails['smtp_tls'] = true
         gitlab_rails['gitlab_email_from'] = "My Email"
    ports:
      - '${SERVE_WEB_PORT}:${SERVE_WEB_PORT}' # 容器内端口必须跟 external_url 端口一致
      # - '443:443'
      - '${SERVE_SSH_PORT}:22'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
    shm_size: '256m' 

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    depends_on:
      - gitlab
    links:
      - gitlab
    volumes:
      - '${GITLAB_RUNNER_HOME}/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
